export var battleBros = [
    // Team 0 (left side)
    {
        id: "01",
        character: 'John Wok',
        x: 400,
        y: 100,
        team: 0,
        isLeader: false,
        // Defined elsewhere
        // - avatarHtmlElement
        // - isTargeted

    },
    {
        id: "02",
        character: 'Clone Wars Chewbacca',
        x: 400,
        y: 300,
        team: 0,
        isLeader: true,
    },
    {
        id: "03",
        character: 'Hera Syndulla',
        x: 400,
        y: 500,
        team: 0,
        isLeader: false,
    },
    {
        id: "04",
        character: 'Mace Windu',
        x: 400,
        y: 700,
        team: 0,
        isLeader: false,
    },
    {
        id: "05",
        character: 'Talia',
        x: 250,
        y: 200,
        team: 0,
        isLeader: false,
    },
    {
        id: "06",
        character: 'Yoda',
        x: 250,
        y: 400,
        team: 0,
        isLeader: false,
    },
    {
        id: "07",
        character: 'Super Striker',
        x: 250,
        y: 600,
        team: 0,
        isLeader: false,
    },
    {
        id: "08",
        character: 'MassiveJabba',
        x: 0,
        y: 350,
        team: 0,
        isLeader: false,
    },

    // Team 1 (right side)
    {
        id: "11",
        character: 'Shadow Menace (Original)',
        x: 1400,
        y: 100,
        team: 1,
        isLeader: false,
    },
    {
        id: "12",
        character: 'Ninja',
        x: 1400,
        y: 300,
        team: 1,
        isLeader: false,
    },
    {
        id: "13",
        character: 'Jedi Bob',
        x: 1400,
        y: 500,
        team: 1,
        isLeader: false,
    },
    {
        id: "14",
        character: 'Red (Samurai)',
        x: 1400,
        y: 700,
        team: 1,
        isLeader: true,
    },
    {
        id: "15",
        character: 'Chuck (Rainbird)',
        x: 1550,
        y: 200,
        team: 1,
        isLeader: false,
    },
    {
        id: "16",
        character: 'Matilda (Druid)',
        x: 1550,
        y: 400,
        team: 1,
        isLeader: false,
    },
    {
        id: "17",
        character: 'SM-33',
        x: 1550,
        y: 600,
        team: 1,
        isLeader: false,
    },
    {
        id: "18",
        character: 'MassiveJabba',
        x: 1700,
        y: 350,
        team: 1,
        isLeader: false,
    },
]
