export const infoAboutCharacters = {
    'jabba': {
        image: 'images/Jabba.png',
        health: 50000,
        protection: 15000,
        speed: 200,
        potency: 100,
        tenacity: 100,
        critChance: 50,
        physicalDamage: 5000,
        specialDamage: 5000,
        armour: 50,
        resistance: 50,
        healthSteal: 100,
        tags: ['lightSide'],
        abilities: ['test1', 'test2'],
        passiveAbilities: ['test3'],
        charDesc: 'insert funny description here',
    },
    'MassiveJabba': {
        image: 'images/Jabba.png',
        imageSize: 200,
        health: 100000,
        protection: 10000,
        speed: 60,
        potency: 100,
        tenacity: 100,
        critChance: 60,
        physicalDamage: 18000,
        specialDamage: 10000,
        armour: 60,
        resistance: 30,
        healthSteal: 20,
        tags: ['lightSide'],
        abilities: ['test1', 'test2'],
        passiveAbilities: ['test3'],
        charDesc: 'insert funny description here',
    },
    'Clone Wars Chewbacca': {
        image: 'images/avatars/CloneWarsChewbacca.png',
        health: 43470 + 52371,
        protection: 10,
        speed: 126,
        potency: 28,
        tenacity: 55,
        critChance: 28.46,
        physicalDamage: 3267,
        specialDamage: 2043,
        armour: 48.23,
        resistance: 41.81,
        healthSteal: 10,
        tags: ['lightSide', 'tank', 'leader', 'galacticRepublic', 'scoundrel'],
        abilities: ['Bowcaster', 'Wookie Rage', 'Defiant Roar'],
        passiveAbilities: ['Wookie Resolve'],
        charDesc: 'Durable Tank with both Taunt and self-Healing',
    },
    'Darth Vader': {
        image: 'images/avatars/DarthVader.png',
        imageSize: 100,
        health: 32156,
        protection: 47828,
        speed: 141,
        potency: 50,
        tenacity: 43,
        critChance: 37.67,
        physicalDamage: 3447,
        specialDamage: 2570,
        armour: 43.36,
        resistance: 34.38,
        healthSteal: 15,
        tags: ['darkSide', 'attacker', 'leader', 'empire', 'sith', 'fleetCommander'],
        abilities: ['Terrifying Swing', 'Force Crush', 'Culling Blade', 'Merciless Massacre'],
        passiveAbilities: ['Inspiring Through Fear', 'No Escape'],
        charDesc: 'Fearsome Attacker that applies AoE Damage Over Time, and crushes debuffed targets for extra turns',
    },
    'Hera Syndulla': {
        image: 'images/avatars/heraSyndulla.png',
        health: 33930 + 34153,
        protection: 0,
        speed: 152,
        potency: 25,
        tenacity: 58,
        critChance: 28.04,
        physicalDamage: 3025,
        specialDamage: 3851,
        armour: 38.5,
        resistance: 43.5,
        healthSteal: 20,
        tags: ['lightSide', 'support', 'leader', 'phoenix', 'rebel'],
        abilities: ['Outwit', 'Play to Strengths', 'Backup Plan'],
        passiveAbilities: [],//'Rise Together'],
        charDesc: 'Cunning Phoenix Support that allows allies to share their Unique abilities with each other',
    },
    'Mace Windu': {
        image: 'images/avatars/MaceWindu.png',
        imageSize: 100,
        health: 36040,
        protection: 39209,
        speed: 143,
        potency: 46,
        tenacity: 47,
        critChance: 23.33,
        physicalDamage: 2689,
        specialDamage: 4679,
        armour: 31.19,
        resistance: 43.31,
        healthSteal: 15,
        tags: ['lightSide', 'tank', 'leader', 'galacticRepublic', 'jedi', 'fleetCommander'],
        abilities: ['Invincible Assault', 'Smite', "This Party's Over"],
        passiveAbilities: ['Take A Seat', 'Vaapad', 'Sense Weakness'],
        charDesc: 'Aggressive Jedi tank with devastating damage if left unchecked',
    },
    'SM-33': {
        image: 'images/avatars/sm33.png',
        imageSize: 100,
        health: 38173 + 37235 + 20000,
        protection: 0,
        speed: 145,
        potency: 36,
        tenacity: 57,
        critChance: 35.5,
        physicalDamage: 1444,
        specialDamage: 1646,
        armour: 46.7,
        resistance: 29.7,
        healthSteal: 25,
        tags: ['darkSide', 'tank', 'attacker', 'droid', 'pirate', 'scoundrel', 'skeletonCrew'],
        abilities: ['Rattling Uppercut', 'Limb From Limb', 'Forearm Bucklers'],
        passiveAbilities: ['First Mate of the Onyx Cinder'],
        charDesc: 'Powerful pirate attacker/tank hybrid who slowly burns away to continuously bombard any challengers with damage.',
    },
    'Talia': {
        image: 'images/avatars/Talia.png',
        imageSize: 100,
        health: 67332,
        protection: 9435,
        speed: 135,
        potency: 41,
        tenacity: 30,
        critChance: 25.29,
        physicalDamage: 2772,
        specialDamage: 4500,
        armour: 30.8,
        resistance: 42.2,
        healthSteal: 10,
        tags: ['darkSide', 'healer', 'leader', 'nightsister'],
        abilities: ['Draining Strike', 'Water of Life', 'Harrowing Assault'],
        passiveAbilities: ['Nightsister Nimbleness'],
        charDesc: 'Aggressive Healer that sacrifices Health so allies can recover Health and Turn Meter',
    },
    'Yoda': {
        image: 'images/avatars/GrandmasterYoda.png',
        imageSize: 100,
        health: 33753,
        protection: 18937,
        speed: 177,
        potency: 56,
        tenacity: 39,
        critChance: 28.42,
        physicalDamage: 2527,
        specialDamage: 4492 / 1.65,
        armour: 31.85,
        resistance: 19.46,
        healthSteal: 5,
        tags: ['lightSide', 'support', 'leader', 'galacticRepublic', 'jedi'],
        abilities: ['Ataru', 'Masterstroke', 'Unstoppable Force', 'Battle Meditation'],
        passiveAbilities: ["Grand Master's Guidance"],
        charDesc: 'Masterful Jedi support that can replicate enemy buffs and share them with allies',
    },
    // --------------------------------------------------------SAVI'S CHARACTERS
    'John Wok': {
        image: 'images/avatars/johnWok.png',
        imageSize: 100,
        health: 50180,
        protection: 8120,
        speed: 143,
        potency: 36,
        tenacity: 41,
        critChance: 34,
        physicalDamage: 3400,
        specialDamage: 3250,
        armour: 25,
        resistance: 18,
        healthSteal: 18,
        tags: ['neutral', 'attacker', 'leader', 'asian', 'earthling'],
        abilities: ['Slipper Slam', 'Belt Flashbang', 'Belt Nunchuck', 'Minute Rice in 59 Seconds'],
        passiveAbilities: [],
        charDesc: 'I once saw Wok discipline three men in his offbrand adidas.',
    },
    'The Fallen': {
        image: 'images/Jabba.png',
        imageSize: 200,
        health: 75000,
        protection: 75000,
        speed: 70,
        potency: 82,
        tenacity: 94,
        critChance: 50,
        physicalDamage: 18000,
        specialDamage: 10000,
        armour: 36,
        resistance: 42,
        healthSteal: 0,
        tags: ['neutral', 'massive', 'tank', 'leader', 'ancient'],
        abilities: ['Massive Crush', 'Septuple Lightsaber Slash', 'Unpreventable', 'Second Chance'],
        passiveAbilities: ['I Have Been Summoned', 'The Fall'],
        charDesc: 'Heed my broken words...',
    },
    // --------------------------------------------------------SUPERPIG'S BRAVADO
    'Business Pig': {
        image: 'images/avatars/businessPig.png',
        imageSize: 100,
        health: 53200,
        protection: 0,
        speed: 139,
        potency: 42,
        tenacity: 43,
        critChance: 27,
        physicalDamage: 4300,
        specialDamage: 3250,
        armour: 31,
        resistance: 27,
        healthSteal: 5,
        tags: ['lightSide', 'support', 'leader', 'earthling', 'superpigsBravado'],
        abilities: ['Thwart the Plan', 'Important Meeting', 'Pig Profit', 'Oinks of Approval'],
        passiveAbilities: ['Large Partnership', 'Very Important Pig'],
        charDesc: 'Business Pig is here to sabotage any future competitors to his prosperous business.',
    },
    // --------------------------------------------------------OLIV'S CHARACTERS
    'Super Striker': {
        image: 'images/avatars/superStriker.png',
        imageSize: 100,
        health: 28450,
        protection: 37828,
        speed: 172,
        potency: 55,
        tenacity: 22,
        critChance: 47.23,
        physicalDamage: 4447,
        specialDamage: 4570,
        armour: 23.36,
        resistance: 32.34,
        healthSteal: 20,
        tags: ['neutral', 'attacker', 'mercenary', 'oliv', 'unalignedForceUser'],
        abilities: ['Lethal Swing', 'Piercing Edge', 'Disruptor Blade', 'Super Strike'],
        passiveAbilities: ['Elimination Protocol'],
        charDesc: 'Powerful foe who crushes enemies with repeated target locks and combos down upon killing an enemy.',
    },
    // --------------------------------------------------------JAMES' CHARACTERS
    'Shadow Menace (Original)': {
        image: 'images/avatars/shadowMenaceOriginal.png',
        imageSize: 100,
        health: 32945,
        protection: 39273,
        speed: 163,
        potency: 49,
        tenacity: 42,
        critChance: 57.23,
        physicalDamage: 3990,
        specialDamage: 3870,
        armour: 37.36,
        resistance: 28.34,
        healthSteal: 8,
        tags: ['darkSide', 'attacker', 'mandalorian', 'scoundrel', 'shadowMenace'],
        abilities: ['Cloning Strike', 'Sabre Storm', 'Rotating Blades', 'Cut it short'],
        passiveAbilities: ['Prime Era', 'Reign of Mandalore'],
        charDesc: 'Powerful mandalorian adversary who attacks many times.',
    },
    // --------------------------------------------------------ERIK'S CHARACTERS
    'Ninja': {
        image: 'images/avatars/ninja.png',
        imageSize: 100,
        health: 19945,
        protection: 27234,
        speed: 182,
        potency: 76,
        tenacity: 54,
        critChance: 49,
        physicalDamage: 5300,
        specialDamage: 4500,
        armour: 26,
        resistance: 32,
        healthSteal: 25,
        tags: ['darkSide', 'attacker', 'sith', 'ninja'],
        abilities: ['Sword Slash', 'Sneak Attack', 'Dread Slash'],
        passiveAbilities: ['Trust is Key to Victory', 'A Ninja Way is Stealth'],
        charDesc: 'Powerful sith foe who hits for powerful damage while remaining in stealth, away from danger.',
    },
    // --------------------------------------------------------OUR CHARACTERS
    'Goosey': {
        image: 'images/avatars/goosey.png',
        imageSize: 90,
        health: 42340,
        protection: 20,
        speed: 129,
        potency: 62,
        tenacity: 73,
        critChance: 54,
        physicalDamage: 2190,
        specialDamage: 2503,
        armour: 68,
        resistance: 58,
        healthSteal: 12,
        tags: ['neutral', 'attacker', 'leader', 'earthling', 'bird'],
        abilities: ['Gooseballs', 'Honk of Approval', 'Belly Bounce', 'Gooseball Barrage'],
        passiveAbilities: ['Quick Balls', 'Gooseys Protection'],
        charDesc: 'Fearless attacker who assists his allies through defence and offence simultaneously!',
    },
    'Jedi Bob': {
        image: 'images/avatars/jediBob.png',
        imageSize: 100,
        health: 30000,
        protection: 40000,
        speed: 166,
        potency: 78,
        tenacity: 23,
        critChance: 28,
        physicalDamage: 3900,
        specialDamage: 2700,
        armour: 46,
        resistance: 32,
        healthSteal: 5,
        tags: ['neutral', 'lightSide', 'darkSide', 'attacker', 'tank', 'support', 'healer', 'jedi', 'unalignedForceUser'],
        abilities: ['Bob Bash', 'Bob Force', 'Bob Blast'],
        passiveAbilities: [],
        charDesc: 'Mysterious, all powerful, and wise. He is the one who will save us all.',
    },
    // --------------------------------------------------------ANGRY BIRDS EPIC CHARACTERS
    'Red (Samurai)': {
        image: 'images/avatars/redSamurai.png',
        imageSize: 100,
        health: 90000,
        protection: 3000,
        speed: 132,
        potency: 32,
        tenacity: 56,
        critChance: 60.23,
        physicalDamage: 8000,
        specialDamage: 3570,
        armour: 33.36,
        resistance: 32.34,
        healthSteal: 20,
        tags: ['neutral', 'tank', 'bird', 'earthling'],
        abilities: ['Dragon Strike', 'Defensive Formation', 'Heroic Strike'],
        passiveAbilities: [],
        charDesc: 'Protects the party. A real hero!',
    },
    'Chuck (Rainbird)': {
        image: 'images/avatars/chuckRainbird.png',
        imageSize: 100,
        health: 47000,
        protection: 3000,
        speed: 171,
        potency: 54,
        tenacity: 15,
        critChance: 30,
        physicalDamage: 8250,
        specialDamage: 4250,
        armour: 25.36,
        resistance: 42.34,
        healthSteal: 10,
        tags: ['neutral', 'healer', 'bird'],
        abilities: ['Acid Rain', 'Healing Rain', 'Speed of Light'],
        passiveAbilities: [],
        charDesc: 'A powerful wizard. Deals damage to all enemies at once!',
    },
    'Matilda (Druid)': {
        image: 'images/avatars/matildaDruid.png',
        imageSize: 100,
        health: 70000,
        protection: 3000,
        speed: 145,
        potency: 49,
        tenacity: 50,
        critChance: 40,
        physicalDamage: 7350,
        specialDamage: 4250,
        armour: 35.36,
        resistance: 22.34,
        healthSteal: 20,
        tags: ['neutral', 'healer', 'bird'],
        abilities: ['Thorny Vine', 'Regrowth', 'Matildas Medicine'],
        passiveAbilities: [],
        charDesc: 'A strong healer who also packs quite a punch!',
    },
    // --------------------------------------------------------KRAYT DRAGON RAID
    'KraytDragon': {
        image: 'images/KraytDragon.png',
        imageSize: 200,
        speed: 120 * 10,
        health: 1000000,
        abilities: ['kraytBasicAttack', 'kraytAcidPuke', 'kraytEatEnemy', 'kraytBurrow', 'kraytUnburrow'],
        attacksPerTurn: 2,
    },
    'Explosives': {
        image: 'images/Explosives.png',
        imageSize: 100,
        speed: 0,
        health: 5,
    },
    'Dathcha': {
        image: 'images/Dathcha.png',
        imageSize: 100,
        speed: 157,
        health: 30000,
        abilities: ['dathchaHitAndRun'],
    },
    'Boba Fett': {
        image: 'images/BobaFett.png',
        imageSize: 100,
        speed: 167,
        health: 29000,
        abilities: ['bobaEE3Carbine'],
    },
    'Mando': {
        image: 'images/Mando.png',
        imageSize: 100,
        speed: 164,
        health: 36000,
        abilities: ['mandoSwiftShot'],
    },
    'Jango Fett': {
        image: 'images/JangoFett.png',
        imageSize: 100,
        speed: 178,
        health: 35000,
        abilities: ['jangoUnscrupulousGunfire'],
    },
    'Cad Bane': {
        image: 'images/CadBane.png',
        imageSize: 100,
        speed: 133,
        health: 33000,
        abilities: ['cadBaneGunSlinger'],
    },
}